Adding interactive plotting option.
biomass-dev/biomass pull request #144
Opened 2022-06-30 07:07 UTC by formersbach

Resolves issue #143

2022-06-30 07:22 UTC, himoto commented on biomass/graph.py
> +        which_controls : list[str] = []
1. it's not a good idea to have a mutable default argument, in this case a dictionary ([see here for explanation](https://docs.python-guide.org/writing/gotchas/)).
2. Use `List` instead of `list`.

```python
which_controls: Optional[List[str]] = None
...
if which_controls is None:
    which_controls = []

2022-06-30 07:27 UTC, himoto requested changes
Hi @formersbach, thanks for the pull request!
Regarding errors in pre-commit, now the code contains many white spaces.
If you use VScode, you can visualize them by using [Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces).

2022-06-30 07:35 UTC, himoto commented on biomass/graph.py
> +import networkx as nx
`nx` is not used.

2022-06-30 07:44 UTC, formersbach commented on biomass/graph.py
> +import networkx as nx
Removed.

2022-06-30 15:07 UTC, himoto commented
Minor updates:
- Remove Examples section in the docstring of `to_graph()` as it is in `static_plot()`
- Make code more *pythonic*
  ```python
  # Do not write xxx (bool) is True/False, e.g.,
  if xxx is True:
      ...
  # This should be
  if xxx:
      ...
  # if xxx is not boolean type, it should raise TypeError
  ```

2022-07-01 02:22 UTC, himoto commented on biomass/graph.py
> +            )
I think it' reasonable to raise `TypeError` here.

2022-07-01 02:22 UTC, himoto commented on biomass/graph.py
> +            )
Why do we need `elif ... else ...` block?
Because `use_flux` is not user-defined but internal variable, it must be boolean type. `if not use_flux ... else ...` seems to be enough.

2022-07-01 02:38 UTC, formersbach commented on biomass/graph.py
> +            )
Will change, guess I went overboard with the errors!

2022-07-01 04:07 UTC, himoto commented
Thanks for implementing amazing functions, @formersbach!

2022-07-01 04:07 UTC, merged