Transfer graphing from BioMass to Text2Model
biomass-dev/biomass pull request #177
Opened 2022-08-23 08:26 UTC by formersbach

This pull request transfers the graphing capabilities from the BioMass level to the Text2Model level.

2022-08-23 08:28 UTC, formersbach commented
Hey @himoto 
Please review whether I correctly changed `model_object.py`  especially careful!

2022-08-23 09:26 UTC, himoto requested changes
Thanks for your PR, looks so nice to me!
Before merging into master, I have a small request.
Please refer to my comments.

2022-08-23 09:26 UTC, himoto commented on biomass/construction/text2model.py
> +from pyvis.network import Network
Currently biomass should be able to use without installing `pygraphviz` and `pyvis` (see #162).
Can you please move these imports from top-level to inside-function?
Also, remember to write:
```python
try:
    import pygraphviz as pgv
except ImportError:
    print("pygraphviz is required to run this function.")
```
in the beginning of `graph()` property and 
```python
try:
    from pyvis.network import Network
except ImportError:
    print("pyvis is required to run this function.")
```
for `dynamic_plot()` function.

2022-08-23 09:35 UTC, himoto commented
Hi @formersbach, can you please update .pre-commit-config.yaml file?
https://github.com/biomass-dev/biomass/blob/2e2bcd783806748d64f27e9563ffded14c3e3485/.pre-commit-config.yaml#L13
In line 13, please bump python version from 3.7 to 3.8 in order to support walrus operator (:=).

2022-08-23 10:22 UTC, himoto commented
**Question:**
Does your updates affect [`test_graph.py`](https://github.com/biomass-dev/biomass/blob/master/tests/test_graph.py)?
If yes, please also update the test code to be compatible the latest graphing method.

2022-08-24 01:10 UTC, formersbach commented on biomass/construction/text2model.py
> +from pyvis.network import Network
Woops, good call. Thanks for noticing. 
Should I also do the same with future features such as the steady state analysis?

2022-08-24 08:05 UTC, himoto commented on biomass/construction/text2model.py
> +from pyvis.network import Network
We can discuss when you raise an issue. Please let me know new dependencies (packages) in the new feature.
Regarding `the steady state analysis', in my opinion it is ok to add `sympy` to requirements.txt

2022-08-24 08:08 UTC, himoto approved these changes

2022-08-24 08:10 UTC, himoto commented
Thanks @formersbach! I will soon merge these changes into master.

2022-08-24 09:18 UTC, merged